image: alpine

stages:
  - build
  - test
  - deploy

compile:
    stage: build
    image: gcc
    before_script:
        - apk update && apk add cmake make gcc ccache
        - mkdir -p ccache
        - export CCACHE_BASEDIR=$(PWD)
        - export CCACHE_DIR=$(PWD)/ccache
    script:
        - cmake -B build/ -DCMAKE_BUILD_TYPE=Debug
        - cmake --build build/ --config Debug
    artifacts:
        paths:
            - build/
    cache:
        paths:
            - "*.o"
            - ccache/

docs:
    stage: build
    before_script:
        - apk update && apk add cmake make doxygen graphviz
    script:
        - cmake -B build -DCMAKE_BUILD_TYPE=Debug
        - cmake --build build/ --config Debug --target docs
    artifacts:
        paths:
            - build/docs/html


test:
    stage: test
    image: gcc
    script:
        - make --build build/ --config Debug --target test
    dependencies:
        - compile
    needs:
        - compile

pages:
    stage: deploy
    script:
        - mkdir public
        - cp -r build/docs/html public
    artifacts:
        paths:
            - public
    dependencies:
        - docs
    needs:
        - docs
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
