name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Debug

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install CCache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ runner.os }}-${{ env.BUILD_TYPE }}
      - name: Install Dependencies
        run: pip install gcovr
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSPECULA_BUILD_TESTING=TRUE -DSPECULA_ENABLE_COVERAGE=TRUE
      - name: Build Tests
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Run Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
      - name: Generate Coverage Report
        run: gcovr --xml-pretty --print-summary -o coverage.xml --root ${{github.workspace}} --object-directory ${{github.workspace}}/build --exclude ${{github.workspace}}/tests --exclude ${{github.workspace}}/app
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
