name: Release

on:
  workflow_dispatch:
  push:
    tags: ["*"]

env:
  BUILD_TYPE: Release

jobs:
  Docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt install -y graphviz
          wget https://www.doxygen.nl/files/doxygen-1.9.3.linux.bin.tar.gz
          tar -xf doxygen-1.9.3.linux.bin.tar.gz
          cd doxygen-1.9.3 && sudo make install
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSPECULA_ENABLE_DOCUMENTATION=TRUE
      - name: Generate Docs
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target docs-coverage
      - name: Publish Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ${{github.workspace}}/build/docs/html
